<link rel="stylesheet" href="${basePath}/resources/plugins/bootstrap/css/bootstrap.css">
<link rel="stylesheet" href="${basePath}/resources/plugins/bootstrap/table/bootstrap-table.css">
<link rel="stylesheet" href="${basePath}/resources/plugins/icheck/skins/all.css">
<link rel="stylesheet" href="${basePath}/resources/lap/css/lap-table.css">
<link rel="stylesheet" href="${basePath}/resources/lap/css/lap-common.css">
<link rel="stylesheet" href="${basePath}/resources/plugins/mC/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="${basePath}/resources/plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="${basePath}/resources/layui/css/layui.css">
<link rel="stylesheet" href="${basePath}/resources/lap/css/lap-skin.css">
<link href="${basePath}/resources/plugs/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet"/>